const product = {
    fashion: [{
      id: 1,
      photo: require('../img/tshirt.png'),
      name: 'Camisa',
      description: 'Camisa de spider-man muy masculina',
      price: '100000',
      discount: '95000',
      offerValue: '5%OFF',
      characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
      master: require('../img/mastercard.png'),
      visa: require('../img/visa.png'),
      bancolombia: require('../img/bancolombia.png'),
      status: 'Si'
    },
    {
      id: 2,
      photo: require('../img/pant.jpg'),
      name: 'Pantalón',
      description: 'Pantalones oscuros para trabajar',
      price: '400000',
      discount: '95000',
      characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
      master: require('../img/mastercard.png'),
      visa: require('../img/visa.png'),
      bancolombia: require('../img/bancolombia.png'),
      status: 'Si'
    },
    {
      id: 3,
      photo: require('../img/shoes.png'),
      name: 'Zapatos',
      description: 'Tenis Jordan 4 azul con blanco',
      price: '2000000',
      discount: '1',
      characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
      master: require('../img/mastercard.png'),
      visa: require('../img/visa.png'),
      bancolombia: require('../img/bancolombia.png'),
      status: 'Si'
    },
    {
      id: 4,
      photo: require('../img/jacket.png'),
      name: 'Chaqueta',
      description: 'Chaqueta impermeable de color verde',
      price: '200000',
      discount: '130000',
      offerValue: '35%OFF',
      characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
      master: require('../img/mastercard.png'),
      visa: require('../img/visa.png'),
      bancolombia: require('../img/bancolombia.png'),
      status: 'Si'
    },
    {
      id: 5,
      photo: require('../img/hoddie.png'),
      name: 'Saco',
      description: 'Saco medio formal color verde',
      price: '250000',
      discount: '95000',
      characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
      master: require('../img/mastercard.png'),
      visa: require('../img/visa.png'),
      bancolombia: require('../img/bancolombia.png'),
      status: 'Si'
    },
    {
      id: 6,
      photo: require('../img/littlePant.jpg'),
      name: 'Pantaloneta',
      description: 'Pantalonea pequeña de color amarillo con negro',
      price: '100000',
      discount: '95000',
      offerValue: '5%OFF',
      characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
      master: require('../img/mastercard.png'),
      visa: require('../img/visa.png'),
      bancolombia: require('../img/bancolombia.png'),
      status: 'Si'
    }
],
    homeCategory:[{
        id: 7,
        photo: require('../img/broom.jpg'),
        name: 'Escoba',
        description: 'Escoba pequeña muy suave',
        price: '100000',
        discount: '95000',
        offerValue: '5%OFF',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 8,
        photo: require('../img/mop.png'),
        name: 'Trapeadora',
        description: 'Trapeadora de defensa personal',
        price: '700000',
        discount: '95000',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 9,
        photo: require('../img/chair.jpg'),
        name: 'Silla',
        description: 'Silla de madera en color negro',
        price: '4700000',
        discount: '700000',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 10,
        photo: require('../img/soap.png'),
        name: 'Jabón',
        description: 'Jabón para tocador de menta',
        price: '200000',
        discount: '130000',
        offerValue: '35%OFF',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 11,
        photo: require('../img/cleaner.jpg'),
        name: 'Fabuloso',
        description: 'Jabón limpia pisos con olor a rosas',
        price: '100000',
        discount: '95000',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 12,
        photo: require('../img/cook.png'),
        name: 'Sarten',
        description: 'Juego de sartenes de acero inoxidable',
        price: '100000',
        discount: '95000',
        offerValue: '5%OFF',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      }
    ],
      makeup: [{
        id: 13,
        photo: require('../img/pencil.png'),
        name: 'Lapiz',
        description: 'Lapiz maquillador',
        price: '100000',
        discount: '95000',
        offerValue: '5%OFF',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 14,
        photo: require('../img/soapFace.png'),
        name: 'Jabón',
        description: 'Jabón dermatologico para el rostro',
        price: '540000',
        discount: '95000',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
    
      },
      {
        id: 15,
        photo: require('../img/pen.png'),
        name: 'Labial',
        description: 'Labial rojo con acabado mate',
        price: '500000',
        discount: '700000',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 16,
        photo: require('../img/sunFactor.png'),
        name: 'Bloqueador',
        description: 'Bloqueador solar de 1000ml',
        price: '200000',
        discount: '130000',
        offerValue: '35%OFF',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 17,
        photo: require('../img/compact.png'),
        name: 'Polvo',
        description: 'Polvo compacto con espejo',
        price: '100000',
        discount: '95000',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 18,
        photo: require('../img/face.png'),
        name: 'Mascarilla',
        description: 'Mascarilla de aguacate para la cara',
        price: '100000',
        discount: '95000',
        offerValue: '5%OFF',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 19,
        photo: require('../img/beltPet.png'),
        name: 'Correa',
        description: 'Correa dinamica para mascotas',
        price: '100000',
        discount: '95000',
        offerValue: '5%OFF',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      }
    ],
      pet: [{
        id: 20,
        photo: require('../img/ball.png'),
        name: 'Pelota',
        description: 'Pelota saltarina para mascotas',
        price: '400000',
        discount: '95000',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 21,
        photo: require('../img/drink.png'),
        name: 'Bebedero',
        description: 'Bebedero para mascotas inoxidable',
        price: '2000000',
        discount: '700000',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 22,
        photo: require('../img/eat.jpg'),
        name: 'Comedero',
        description: 'Comedero para mascotas de varios colores',
        price: '200000',
        discount: '130000',
        offerValue: '35%OFF',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 23,
        photo: require('../img/shirt.png'),
        name: 'Camisa',
        description: 'Camisa comodas para mascotas',
        price: '2530000',
        discount: '95000',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 24,
        photo: require('../img/bone.png'),
        name: 'Hueso',
        description: 'Hueso para mascotas comestible',
        price: '100000',
        discount: '95000',
        offerValue: '5%OFF',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      }
    ],
      technology: [{
        id: 25,
        photo: require('../img/headphones.png'),
        name: 'Audífonos',
        description: 'Audífonos inalámbricos grises',
        price: '100000',
        discount: '95000',
        offerValue: '5%OFF',
        characteristics: 'Marca Sony, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 26,
        photo: require('../img/mouse.png'),
        name: 'Mouse',
        description: 'Mouse gamer RedDragon con luces',
        price: '500000',
        discount: '95000',
        characteristics: 'Marca RedDragon, Grises, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 27,
        photo: require('../img/tecno.png'),
        name: 'Celular',
        price: '4500000',
        description: 'Celular Xiaomi azul brillante',
        discount: '700000',
        characteristics: 'Marca Xiaomi, Azul, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 28,
        photo: require('../img/battery.jpg'),
        name: 'Batería',
        description: 'Batería portátil con linterna',
        price: '200000',
        discount: '130000',
        offerValue: '35%OFF',
        characteristics: 'Marca Batería, Negra, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 29,
        photo: require('../img/watch.png'),
        name: 'Reloj',
        description: 'Reloj digital con manillas azules',
        price: '800000',
        discount: '95000',
        characteristics: 'Marca Batería, Azul, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      },
      {
        id: 30,
        photo: require('../img/camera.png'),
        name: 'Cámara',
        description: 'Cámara digital Nikon negra',
        price: '100000',
        discount: '95000',
        offerValue: '5%OFF',
        characteristics: 'Marca Nikon, Negra, 7 horas de duración, trae cargador',
        master: require('../img/mastercard.png'),
        visa: require('../img/visa.png'),
        bancolombia: require('../img/bancolombia.png'),
        status: 'Si'
      }],
    }

  module.exports = product;